Add laravel5.8 support
ellipsesynergie/oauth2-server-laravel pull request #1
Opened 2021-09-03 13:33 UTC by alexbolductremblay

##Description
Ajouté la compatibilité a Laravel 5.8

##Reference 
https://trello.com/c/fCS0llto

2021-11-11 21:17 UTC, maximebeaudoin requested changes
Je comprend pas trop ce PR. Pourquoi ça pointe vers la version 4.0 du package ?. Présentement, si je me trompe pas. On utilise la version 5.3.* (qui est déjà une version custom) dans epsylio-backend. Voir https://github.com/ellipsesynergie/epsylio-backend/blob/master/composer.json#L18. Normalement, on devrait créer un PR vers la branche master, pour éventuellement créer un nouveau tag pour supporter la dernière version 5.8 de laravel. Ensuite on va pouvoir créer un nouveau tag à partir de ça.

2021-11-11 21:17 UTC, maximebeaudoin commented on .idea/oauth2-server-laravel.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Pourquoi il a les fichiers .idea dans ce PR ?

2021-11-11 21:22 UTC, maximebeaudoin commented
Peut-être juste changer la target de ce PR @alexbolductremblay ?

2021-11-17 19:18 UTC, flbergeron commented on .idea/oauth2-server-laravel.iml
> +<?xml version="1.0" encoding="UTF-8"?>
@alexbolductremblay 

enlève le dossier .idea, il doit pas être commité sur le repo. Ajoute au .gitignore le dossier .idea

2021-11-26 13:31 UTC, maximebeaudoin requested changes

2021-11-26 13:31 UTC, maximebeaudoin commented on composer.json
> +            "dev-master": "5.6-dev"
Le chiffre représente le numéro de la prochaine release. Ce devrait être `5.4-dev`

2021-11-26 13:31 UTC, maximebeaudoin commented on composer.json
> +        "league/oauth2-server": "dev-add-symfony4-support"
Ce devrait pointer vers une version fixe avant de descendre dans master. Est-ce que notre version custom de `league/oauth2-server` est prête à avoir son tag ?

2021-11-26 14:01 UTC, alexbolductremblay commented on composer.json
> +        "league/oauth2-server": "dev-add-symfony4-support"
Yes, on l'avais fait tout les 2 cette modif là elle est prete.

2021-11-26 14:46 UTC, maximebeaudoin approved these changes
Il resterait à mettre à jour le tag du package `league/oauth2-server` et ce serait bon pour moi.

2021-12-01 13:56 UTC, merged